name: 步步宝 

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 0-23 * * ?'
     
  watch:
      types: [started]
    repository_dispatch:
      types: bububao

jobs:
  build:
    env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BBB_CASH: ${{ secrets.BBB_CASH}}


    runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          node Task/bububao.js
          
      - name: '运行 【步步宝】'
        if: env.fqkkurl
        run: |
          node Task/bububao.js

