# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
name: 中青看点助力

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '*/30 0-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/chenlong7353/js.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node

      - name: '运行 【youthshare】'
        run: |
          cd ~/js   
          node Task/youthshare.js

